name: $(Date:yyyyMMdd)$(Rev:.r)

trigger: [master]

variables:
  SourceMarkdown: Sample.md
  OutputFileName: Sample
  Title: Sample

pool:
  name: Hosted VS2017
  demands: npm

steps:
- task: Npm@1
  displayName: 'Install html5-to-pdf'
  inputs:
    command: custom
    verbose: false
    customCommand: 'install -g html5-to-pdf'

- task: knom.markdown-task.markdown-2-html.Markdown2Html@3
  displayName: 'Generate html'
  inputs:
    markdownPath: $(SourceMarkdown)
    templatePath: 'page-template.html'
    parameters: '{"title": "$(Title)", "version": "$(Build.BuildNumber)"}'
    htmlPath: '$(Build.ArtifactStagingDirectory)\$(OutputFileName).html'
    passThruHTML: true

- script: 'copy $(Build.SourcesDirectory)\page-template.css $(Build.ArtifactStagingDirectory)\page-template.css'
  displayName: 'Copy css to artifacts directory'

- script: 'html5-to-pdf --print-background --page-size A5 -o $(Build.ArtifactStagingDirectory)\$(OutputFileName).pdf --template-path $(Build.ArtifactStagingDirectory)\ $(Build.ArtifactStagingDirectory)\$(OutputFileName).html'
  displayName: 'Generate pdf'

- task: PublishBuildArtifacts@1
  displayName: 'Upload generated html and pdf'
