name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir output
          cp page-template.css output/page-template.css
      - uses: docker://pandoc/latex:2.9
        with:
          args: --output=output/result.pdf Sample.md
      - uses: docker://pandoc/latex:2.9
        with:
          args: --template=page-template.html -t html --output=output/result.html Sample.md
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
